import os
from datetime import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchemaProber Alignment Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: auto; padding: 20px; }}
        .header {{ background: #f8f9fa; border: 1px solid #ddd; padding: 20px; margin-bottom: 30px; border-left: 5px solid #005596; }}
        .logo {{ font-family: monospace; white-space: pre; color: #005596; font-weight: bold; font-size: 12px; }}
        .lab-info {{ font-size: 0.9em; color: #555; margin-top: 10px; }}
        .summary-table {{ width: 100%; border-collapse: collapse; margin-bottom: 40px; }}
        .summary-table th, .summary-table td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        .summary-table th {{ background-color: #005596; color: white; }}
        .match-card {{ border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-bottom: 30px; }}
        .match-title {{ background: #e9ecef; padding: 10px; border-radius: 4px; font-weight: bold; display: flex; justify-content: space-between; }}
        .attr-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-top: 15px; font-family: monospace; font-size: 0.9em; }}
        .attr-item {{ color: #28a745; }}
        .gap-item {{ color: #dc3545; background: #fff5f5; padding: 5px; border-radius: 3px; border: 1px solid #ffc9c9; margin: 5px 0; font-family: monospace; }}
        .footer {{ font-size: 0.8em; color: #888; text-align: center; margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; }}
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">{logo}</div>
        <h2>SchemaProber Report</h2>
        <div class="lab-info">{lab_info}</div>
    </div>

    <h3>Summary Alignment</h3>
    <p><strong>Query Size:</strong> {query_count} Attributes</p>
    <table class="summary-table">
        <thead>
            <tr>
                <th>Target Schema</th>
                <th>Identity Score</th>
                <th>Common Attributes</th>
            </tr>
        </thead>
        <tbody>
            {summary_rows}
        </tbody>
    </table>

    <h3>Detailed Alignments</h3>
    {alignment_details}

    <div class="footer">
        Generated by CIDGOH SchemaProber on {timestamp}
    </div>
</body>
</html>
"""

def generate_html_report(matches, query_attributes, logo_text, lab_info, output_path="report.html"):
    query_set = set(query_attributes)
    summary_rows = ""
    alignment_details = ""

    for m in matches:
        target_attrs = {attr[1] for attr in m.matching_attributes}
        unmatched = sorted(list(query_set - target_attrs))
        common_count = len(m.matching_attributes)
        
        # Build Summary Row
        summary_rows += f"<tr><td>{m.target_schema_name}</td><td>{m.similarity_score:.1%}</td><td>{common_count} / {len(query_attributes)}</td></tr>"

        # Build Details
        shared_html = "".join([f'<div class="attr-item">✅ {a[0]}</div>' for a in sorted(m.matching_attributes)])
        gaps_html = "".join([f'<div class="gap-item">❌ MISSING: {a}</div>' for a in unmatched])
        
        alignment_details += f"""
        <div class="match-card">
            <div class="match-title">
                <span>> {m.target_schema_name}</span>
                <span>ID: {m.target_schema_id}</span>
            </div>
            <p><strong>Similarity Score:</strong> {m.similarity_score:.1%}</p>
            <div class="attr-grid">{shared_html}</div>
            <h4 style="color:#dc3545;">Gaps Identified ({len(unmatched)})</h4>
            <div>{gaps_html if gaps_html else '<em>No gaps found. Perfect match.</em>'}</div>
        </div>
        """

    full_html = HTML_TEMPLATE.format(
        logo=logo_text.replace("\n", "<br>"),
        lab_info=lab_info.replace("\n", "<br>"),
        query_count=len(query_attributes),
        summary_rows=summary_rows,
        alignment_details=alignment_details,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_html)
    
    return os.path.abspath(output_path)